kind: pipeline
type: docker
name: default

trigger:
  event:
    - tag

steps:
  - name: publish-wolf-release
    image: plugins/docker
    settings:
      dockerfile: docker/wolf.Dockerfile
      registry: registry.helixml.tech
      repo: registry.helixml.tech/helix/wolf
      username: admin
      password:
        from_secret: helix_registry_password
      tags:
        - ${DRONE_TAG}
        - latest
      platform: linux/amd64
      build_args:
        - BASE_IMAGE=ghcr.io/games-on-whales/gstreamer:1.26.7
